name = "template"
main = "worker/src/index.ts"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "dist" }

[[d1_databases]]
binding = "DB"
database_name = "cf-harborline-template-demo"
database_id = "0bcfb088-88d7-4d37-b4de-5cc24eca35b0"
